source 'https://rubygems.org'

gem 'chronic'
gem 'cucumber',                   '~> 3.0'
gem 'rspec-expectations',         '~> 3.3.0'
gem 'factory_girl',               '~> 4.5.0'
gem 'pry',                        '~> 0.10.3'
gem 'parallel_tests',             '~> 2.7'
gem 'rake',                       '~> 10.4.2'
gem 'rubysl-securerandom',        '~> 2.0'
gem 'activesupport'
gem 'httpclient'
gem 'colorize',                   '~> 0.8.1'
gem 'forgery',                    '0.6.0'
gem 'json'
gem 'jsonpath'
gem 'rest-client',                '~> 1.8'
gem 'dotenv',                     '~> 2.2', '>= 2.2.1'
gem "require_all",                '~> 1.3.3'
